export const SITE = {
  website: "https://hackthebrain.dev/",
  author: "Netzy",
  profile: "https://github.com/netzy",
  desc: "Hack your brain",
  title: "hackthebrain",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Edit page",
    url: "https://github.com/netzy/hackthebrain/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "Asia/Seoul",
} as const;
